version: "3"

services:
  app:
  #Build a Dockerfile in the same directory
    build: .
  #Give the container a name(Any)
    container_name: QR-lyc-system
    #You can keep the container running.
    tty: true
    #Mount the files in the directory to the app directory in the container
    volumes: 
      - .:/app
      #Mount port 1000 on the container side to port 8080 on the host side.
    ports:
      - "3000:3000"